# CI jobs to be run upon the code lands to the main branch or GitHub Action test branches.

name: ci-pre-land

on:
  pull_request:
    branches: [main, gha-test-*, aptos*]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: ./.github/actions/build-setup
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - name: cargo clippy
        run: cargo xclippy --workspace --all-targets
      - name: cargo fmt
        run: cargo xfmt --check
      - uses: ./.github/actions/build-teardown

  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: ./.github/actions/build-setup
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: run unit tests
        run: cargo test --workspace --profile ci --no-fail-fast
      - uses: ./.github/actions/build-teardown
